# Generated by Django 4.2 on 2023-10-12 07:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prez_ukaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название ')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Указ президента')),
            ],
            options={
                'verbose_name': 'Указ президента',
                'verbose_name_plural': 'Указ президента',
            },
        ),
    ]
