# Generated by Django 4.2 on 2023-05-15 11:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги ')),
                ('prewiev', ckeditor.fields.RichTextField(verbose_name='Анонс услуги')),
                ('detail', ckeditor.fields.RichTextField(verbose_name='Подробнее о услуге услуги')),
                ('key', models.CharField(max_length=200, verbose_name='Ключ услуги ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/service/', verbose_name='Иконка услуги')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
