# Generated by Django 4.2 on 2023-05-13 12:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_rup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название о нас')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название функций')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Функции предприятия')),
            ],
            options={
                'verbose_name': 'Функции предприятия',
                'verbose_name_plural': 'Функции предприятия',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_map', models.ImageField(blank=True, null=True, upload_to='images/about/', verbose_name='Карта области')),
            ],
            options={
                'verbose_name': 'Карта области',
                'verbose_name_plural': 'Карта области',
            },
        ),
        migrations.CreateModel(
            name='Terretory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Агентство\\филиал\\бюро ')),
                ('terretory', ckeditor.fields.RichTextField(verbose_name='Территория обслуживания ')),
                ('adress', models.CharField(max_length=200, verbose_name='Адресс ')),
                ('tel', models.CharField(max_length=200, verbose_name='Телефон ')),
                ('mail', models.CharField(max_length=200, verbose_name='Эл.почта ')),
                ('rs_bank', ckeditor.fields.RichTextField(verbose_name='Расчётный счёт банка ')),
            ],
            options={
                'verbose_name': 'ТОРы',
                'verbose_name_plural': 'ТОРы',
            },
        ),
    ]
