# Generated by Django 4.2 on 2023-05-15 06:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_rup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terretory',
            name='rs_bank',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Расчётный счёт банка '),
        ),
    ]
