# Generated by Django 4.2 on 2023-04-28 08:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grafik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название графика')),
                ('post', ckeditor.fields.RichTextField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Графики',
                'verbose_name_plural': 'График',
            },
        ),
    ]
