# Generated by Django 4.2 on 2023-05-02 06:16

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideology', '0003_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='post',
        ),
        migrations.AddField(
            model_name='news',
            name='detail_news',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Детальная новость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='preview_news',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='Анонс новости'),
            preserve_default=False,
        ),
    ]
