# Generated by Django 4.2 on 2023-05-05 13:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideology', '0004_remove_news_post_news_detail_news_news_preview_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название статьи/матерьяла')),
                ('post', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'статья/матерьял',
                'verbose_name_plural': 'Статья/Матерьял',
                'ordering': ['-date', 'title'],
            },
        ),
    ]
