# Generated by Django 4.2 on 2023-05-10 13:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideology', '0005_edi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Govment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название символики')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/govment/%Y/%m/%d/', verbose_name='Символика')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание символики')),
            ],
            options={
                'verbose_name': 'Сиволика РБ',
                'verbose_name_plural': 'Символика РБ',
            },
        ),
        migrations.AlterField(
            model_name='edi',
            name='post',
            field=ckeditor.fields.RichTextField(verbose_name='Описание статьи/матерьяла'),
        ),
        migrations.AlterField(
            model_name='grafik',
            name='post',
            field=ckeditor.fields.RichTextField(verbose_name='Описание графика'),
        ),
    ]
