# Generated by Django 4.2 on 2023-05-11 07:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideology', '0006_govment_alter_edi_post_alter_grafik_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название первичной организации')),
                ('image_brsm', models.ImageField(blank=True, null=True, upload_to='images/organizations/%Y/%m/%d/', verbose_name='Символика БРСМ №1')),
                ('image_brsm2', models.ImageField(blank=True, null=True, upload_to='images/organizations/%Y/%m/%d/', verbose_name='Символика БРСМ №2')),
                ('descr_info', ckeditor.fields.RichTextField(verbose_name='Документация/устав')),
                ('descr_about', ckeditor.fields.RichTextField(verbose_name='Структура БРСМ')),
                ('brsm_symbol', models.ImageField(blank=True, null=True, upload_to='images/brsm/%Y/%m/%d/', verbose_name='Фото описание символики')),
                ('brsm_bilet', models.ImageField(blank=True, null=True, upload_to='images/brsm/%Y/%m/%d/', verbose_name='Фото описание билета')),
            ],
            options={
                'verbose_name': 'БРСМ инфо',
                'verbose_name_plural': 'БРСМ инфо',
            },
        ),
        migrations.CreateModel(
            name='BRSM_contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_org', models.CharField(max_length=200, verbose_name='Организация')),
                ('title_adress', models.CharField(max_length=200, verbose_name='Адресс')),
                ('title_email', models.CharField(max_length=200, verbose_name='почта')),
                ('title_job', models.CharField(max_length=200, verbose_name='Должность')),
                ('title_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('photo', models.ImageField(upload_to='images/photo/brsm-contacts', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Контакты БРСМ',
                'verbose_name_plural': 'Контакты БРСМ',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название организации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/organizations/%Y/%m/%d/', verbose_name='Фото для организации')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание организации')),
            ],
            options={
                'verbose_name': 'Общественные организации',
                'verbose_name_plural': 'Общественные организации',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/news/%Y/%m/%d/', verbose_name='Фото главное'),
        ),
    ]
