# Generated by Django 4.2 on 2023-05-11 14:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('another_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название ')),
                ('description', ckeditor.fields.RichTextField(verbose_name='О работе с обращениями')),
            ],
            options={
                'verbose_name': 'О работе с обращениями',
                'verbose_name_plural': 'О работе с обращениями',
            },
        ),
        migrations.CreateModel(
            name='Dop_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название ')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Дополнительная инфрмация')),
            ],
            options={
                'verbose_name': 'Дополнительная инфрмация',
                'verbose_name_plural': 'Дополнительная инфрмация',
            },
        ),
        migrations.CreateModel(
            name='El_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название ')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Электронные обращения')),
            ],
            options={
                'verbose_name': 'Электронные обращения',
                'verbose_name_plural': 'Электронные обращения',
            },
        ),
    ]
