# Generated by Django 4.2 on 2023-04-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/photo/bosses', verbose_name='Фото')),
                ('title_name', models.CharField(max_length=200, verbose_name='ФИО директора')),
                ('title_job', models.CharField(max_length=200, verbose_name='Должность')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Руководство, директор',
                'verbose_name_plural': 'Руководство, директор',
            },
        ),
        migrations.CreateModel(
            name='Filials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/photo/bosses', verbose_name='Фото')),
                ('title_name', models.CharField(max_length=200, verbose_name='ФИО начальника филиала')),
                ('title_job', models.CharField(max_length=200, verbose_name='Должность')),
                ('title_place', models.CharField(max_length=200, verbose_name='Агенство/Филиал')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Руководство, начальник филиала',
                'verbose_name_plural': 'Руководство, начальник филиала',
            },
        ),
        migrations.CreateModel(
            name='First_Zam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/photo/bosses', verbose_name='Фото')),
                ('title_name', models.CharField(max_length=200, verbose_name='ФИО 1-го зама')),
                ('title_job', models.CharField(max_length=200, verbose_name='Должность')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Руководство, 1-й заместитель',
                'verbose_name_plural': 'Руководство, 1-й заместитель',
            },
        ),
        migrations.CreateModel(
            name='Zam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/photo/bosses', verbose_name='Фото')),
                ('title_name', models.CharField(max_length=200, verbose_name='ФИО заместителя')),
                ('title_job', models.CharField(max_length=200, verbose_name='Должность')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Руководство,  заместитель',
                'verbose_name_plural': 'Руководство, заместитель',
            },
        ),
    ]
